# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d77e7e949eb2bb104b5a0ad463028ffd01ecb51e26abf98fff8bfe19c841127da113cb6434279dfaa2c75daa30e84305a9784c9f5ac85d3967ddd2bb1550f3e0

test:
  secret_key_base: b0bd0a94363d44248f03e1745c66e5929277e0c8d171b85f24dca47cc07a3b4b29429d4223aa2afab0d1022c571622a3a574aa1b5d1680bb5809fca456dcbd2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
